name: Deploy to Render

# Este workflow se dispara después de que build-test.yml termine correctamente
on:
  workflow_run:
    workflows: ["Build & Test (.NET 8)"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Render Deploy
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          https://api.render.com/deploy/srv-d3fciqb3fgac73b4in3g

